### PR TITLE
Run deployments in background

### LINKED ISSUE #134: In progress deploy is restarted when navigating
I've noticed that after a deployment is in progress, if you navigate back to any other part of the UI, when you come back to watch the progress, the deployment is restarted from scratch, leaving the previous one unfinished.

It seems that the problem is that the DeploymentOutputStream view, which is used by the iframe showing the output is creating a new deployment process each time.

### PR DESCRIPTION
**Pull request by msurdi**
This fixes #134 by making use of uWSGI spoolers. Documentation needs to be updated but I'd appreciate your opinion on this particular approach. I'd appreciate any feedback so that we can get this merged in.

### CODE REVIEW

**Comment by jproffitt** [comment]
This sounds like an awesome idea! What will happen if someone is not using uWSGI? We definitely need docs on this if it requires extra configuration.

**Comment by msurdi** [comment]
This implementation requires uWSGI. So I suppose we have a few options. First obvious one is making uWSGI a required dependency. If that's not a viable option, we need to consider the other use cases we want to support. I'd say that for running it under Django's built-in server it would be possible to fork a thread and run "synchronously" the deployment task in that thread while the original one ends the request, and then the js code polls the server for task updates. I haven't tried this but it should work. It wouldn't be that reliable of course, but Django's built in server is not recommended for production use anyway, so...

If you want to support other environments, such as gunicorn, etc then that would require more research.

I certainly can update the documentation and maybe find some time to give a try to making this work under Django's runserver. 

As a side note, we've been using this branch this week and it works well for us.

**Comment by paperreduction** [comment]
We love this idea, thanks. Your code looks great, but we are worried about the uwsgi dependency. Lots of folks will just do "runserver" for development, and this would require them to run uwsgi instead. So what we're thinking we need to do is create an API for a pluggable backend that lets you offload tasks to a separate process depending on your environment. So you can use a "dummy" backend, which is the current one, for dev and then use a uwsgi backend like suggested in this PR. 

All that to say, we are working on a task runner backend API so that we can plug in different backends. This will allow us to adapt what you have in this PR.

**Comment by povilasb** [comment]
What's the status of this PR?

**Comment by msurdi** [comment]
We've been using this branch (plus some other minor changes)[1] in production for about a year and works perfectly, but the concern here is what to do in development mode and/or running it without uwsgi, which I think is a valid one.

I can think of two solutions, first one to try/catch importing uwsgi or using a setting and providing mocks so it works in both situations. The second (and maybe easier to implement) would be to just add a Dockerfile, push it to dockerhub and have people running it with just `docker run fabric-bolt ...`, which would make it even more easy to run and will allow it to depend on almost anything without worrying about deployment. That's something we do internally too and works perfectly.


[1] here is the fork we're running, quite outdated as we don't have the time we need to keep it current, but it works for us: https://github.com/qdqmedia/fabric-bolt

**Pull request closed without merging**
